Repository rainlab/builder-plugin, pull requests merged in 2019-07, with the labels that each got.

#288 Added format as a supported property for the DatePicker widget
  classes/StandardControlsRegistry.php
  lang/en/lang.php
Labels: Status: Revision Needed, Type: Maintenance

#291 Allow special default values for certain columns
  classes/DatabaseTableModel.php
  classes/DatabaseTableSchemaCreator.php
  classes/TableMigrationCodeGenerator.php
  lang/en/lang.php
Labels: Status: Completed, Type: Maintenance

#293 "Add ID column" Button for Migration Editor
  assets/js/build-min.js
  assets/js/builder.index.entity.databasetable.js
  behaviors/indexdatabasetableoperations/partials/_tab.htm
  lang/en/lang.php
Labels: Status: Testing Needed, Type: Enhancement
