Repository rainlab/builder-plugin, pull requests merged in 2019-11, with the labels that each got.

#301 Removing date validation
  classes/StandardControlsRegistry.php
  lang/cs/lang.php
  lang/en/lang.php
  lang/es/lang.php
  lang/fa/lang.php
  lang/nl/lang.php
  lang/pl/lang.php
  lang/pt-br/lang.php
Labels: Status: Completed, Type: Enhancement

#304 Ability to order versions list descending
  assets/less/builder.less
  lang/en/lang.php
  widgets/VersionList.php
  widgets/versionlist/partials/_sort.htm
  widgets/versionlist/partials/_toolbar.htm
  widgets/versionlist/partials/_widget-contents.htm
Labels: Status: Revision Needed, Type: Enhancement

#309 Redo of #304
  assets/less/builder.less
  lang/en/lang.php
  widgets/VersionList.php
  widgets/versionlist/partials/_sort.htm
  widgets/versionlist/partials/_toolbar.htm
  widgets/versionlist/partials/_widget-contents.htm
Labels: Status: Testing Needed, Type: Enhancement
